version: '3.7'

services:
    postgres-db:
        restart: always
        image: postgres:latest
        privileged: true
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
            timeout: 45s
            interval: 10s
            retries: 10
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./RestaurantReservation/backend/src/database/postgres/data:/var/lib/postgresql/data/pgdata
        networks:
            restaurant_net:
                aliases:
                    - postgres_net

    api:
        build:
            context: ./RestaurantReservation/backend
            dockerfile: Dockerfile
            target: base
        command: >
            bash -c "
                source .venv/bin/activate &&
                cd src &&
                flask run --host $$(hostname -i)
            "
        volumes:
            - './RestaurantReservation/backend:/api'
        ports:
            - 5000:5000
        environment:
            - FLASK_APP=api
            - FLASK_ENV=development
            - DB_HOST=restaurantreservation_postgres-db_1:5432
        depends_on:
            postgres-db:
                condition: service_healthy
        networks:
            restaurant_net:
                aliases:
                    - api_net

networks:
    restaurant_net:
        driver: bridge
