"""empty message

Revision ID: 51c17f6d6ffe
Revises: 
Create Date: 2021-05-31 00:49:38.203208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c17f6d6ffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sunday', sa.String(), nullable=True),
    sa.Column('monday', sa.String(), nullable=True),
    sa.Column('tuesday', sa.String(), nullable=True),
    sa.Column('wednesday', sa.String(), nullable=True),
    sa.Column('thursday', sa.String(), nullable=True),
    sa.Column('friday', sa.String(), nullable=True),
    sa.Column('saturday', sa.String(), nullable=True),
    sa.Column('hours', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patron_id'], ['patron.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('restaurant_id', 'patron_id', 'start_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('restaurant')
    op.drop_table('patron')
    # ### end Alembic commands ###
