"""empty message

Revision ID: 6e59f5a94fb5
Revises: 51c17f6d6ffe
Create Date: 2021-07-19 19:12:49.367258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e59f5a94fb5'
down_revision = '51c17f6d6ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patron', sa.Column('number', sa.String(), nullable=True))
    op.add_column('patron', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patron', 'email')
    op.drop_column('patron', 'number')
    # ### end Alembic commands ###
